### ISSUE TITLE
[Issue]Komga and Komf Userscript Configuration

### ISSUE THREAD

**Issue by UltramarineSky** [Snd-R/komf-userscript#24]
![截图_20240516193240](https://github.com/Snd-R/komf-userscript/assets/54146035/8978b9bb-de72-45b6-a38a-1a4ed607a231)

I apologize, but I may need some help.
I installed Komga and Komf on my NAS using the following docker-compose configuration and have set them up. I can see from the logs that Komf is already running. However, when I try to install the `komf-userscript` script on my computer using the Edge browser to configure the Komf server, accessing `http://192.168.3.19:8085/` results in a `Network Error`. I would like to ask how I should set this up.
```
version: "3.3"
services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - /share/CACHEDEV1_DATA/Container/komga/config:/config
      - /share/CACHEDEV1_DATA/Container/komga/tmp:/tmp
      - /share/CACHEDEV1_DATA/Container/komga/data:/data
      - /share/CACHEDEV4_DATA/OneLibrary:/ol
      - /share/CACHEDEV4_DATA/Fan:/fan
    ports:
      - 25600:25600
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
      - JAVA_TOOL_OPTIONS=-Xmx4g
      #- KOMGA_CORS_ALLOWED_ORIGINS
    restart: unless-stopped

  komf:
    image: sndxr/komf:latest
    container_name: komf
    ports:
      - 8085:8085
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /share/CACHEDEV1_DATA/Container/komf/config:/config
      - /share/CACHEDEV1_DATA/Container/komga/tmp:/tmp
      - /share/CACHEDEV1_DATA/Container/komga/data:/data
      - /share/CACHEDEV4_DATA/OneLibrary:/ol
      - /share/CACHEDEV4_DATA/Fan:/fan
    restart: unless-stopped
```
log
```

19:50:08.508 [main] INFO io.javalin.Javalin -- Starting Javalin ...
19:50:08.633 [main] INFO io.javalin.Javalin -- Javalin started in 282ms \o/
19:50:08.641 [main] INFO io.javalin.Javalin -- Listening on http://localhost:8085/
19:50:08.662 [main] INFO io.javalin.Javalin -- You are running Javalin 6.1.2 (released February 25, 2024).
19:50:09.315 [OkHttp http://172.29.12.1:25600/...] INFO org.snd.mediaserver.komga.KomgaEventListener -- connected to komga on http://172.29.12.1:25600/
```
